version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
    - 3.0.2
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
